version: '3.9'

services:
  asset:
    image: gymu.asset.service:dev
    restart: always
    command: dev
  api:
    image: gymu.api.service:dev
    restart: always
    command: dev:db:push
  
  analyze:
    image: gymu.analyze.service:dev
    restart: always
    command: dev